name: parallel-test-action
description: Distribute the test files to the shards based on the estimated time from the test reports

inputs:
  working-directory:
    description: Working directory
    required: false
    default: .
  test-files:
    description: Glob pattern of test files
    required: true
  test-report-artifact-name-prefix:
    description: Prefix of the test report artifact name
    required: true
  test-report-branch:
    description: Branch to find the test report artifacts
    required: true
  shard-count:
    description: Number of shards
    required: true
  shards-artifact-name:
    description: Name of the shards artifact
    required: true
    default: parallel-test-shards
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}

outputs:
  shards-directory:
    description: Directory to store the shard files

runs:
  using: 'node20'
  main: 'dist/index.js'
