name: typescript-action
description: Template of TypeScript Action

inputs:
  test-report-branch:
    description: Branch to find the test report artifacts
    required: true
  test-report-artifact-name-prefix:
    description: Prefix of the test report artifact name
    required: true
  token:
    description: GitHub token
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'
